version: '3.8'

services:
  mongo:
    image: docker.io/mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME}
    volumes:
      # database storage
      - mongo-data:/data
    ports:
      - "27017:27017"
    hostname: mongo
    restart: "no"

volumes:
  mongo-data: {}